[package]
name = "spell_check"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pop-launcher = "1.1"
serde = "1.0"
serde_json = "1.0"
toml = "0.5"
distance = "0.4"
